name: 🐛 Bug Report
description: Report a bug in llm-plugin-tester
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `llm-plugin-tester analyze -t gpt-action -m manifest.json`
        2. See error...
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is affected?
      options:
        - Recon (OpenAPI/MCP)
        - Proxy (Interception)
        - Payloads
        - Oracle (Listener)
        - CLI
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.12"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Windows 11 / Ubuntu 22.04 / macOS 14"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Paste any error messages or stack traces
      render: shell
